// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "xAjjbKho7hY2UsBluAYONIkFBVWp6qjlrPWBDS1v75G5mNPiS9EgzoWnhrKdOSoqsYmjN9";
}
}
}

