// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "kR1VvZp94MrmoAbOQih5lRA1Eq8qMW70JVJtWnJOTulhAMfmkvUSTFbuIfqiqMdsWG7P4C";
}
}
}

