// AUTOGENERATED, DO NOT EDIT

namespace XRInternal {
namespace XRAutoGenerated {
public class XRMobileAppKey {
  // %key% will be replaced with the editor-supplied value on build.
  public const string KEY = "1atFZwaoT6XrYKAfvPtejSz5kWzfVOxfAy5ddBfaeT79ApbRMQMZV89W6aaYudxzB5IH4m";
}
}
}

